### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by Aspem** [TilCreator/Tapas-Comic-Downloader#12]
When I try to open the downloader it gives the message: _NoModuleError: no module named 'pyquery'_ and immediately closes.

**Comment by TilCreator** [comment]
Did you follow the Usage section of the README.md?

**Comment by Aspem** [comment]
Never mind, I just realized this is only for Linux. =( Thank for the reply and sorry for wasting your time.

**Comment by TilCreator** [comment]
In theory it sould be no problem running the schript on Windows, I just can't test it.

**Comment by TilCreator** [comment]
Is this issue still active?

**Comment by ONSKJ** [comment]
I am trying to test this on Windows. Everything worked up until Python interpreter (I acessed python through interpreter via cmd) began executing code. It was unable to execute past line 2, having the same issue Aspen is having: "No module named 'pyquery' "...

I read README but it still can't get it to work... Maybe I am misunderstanding something? I didn't get a syntax error so it was trying to execute the code... but idk, Is it even possible?

**Comment by TilCreator** [comment]
Have you installed the modules?
```
pip install -r requirenments.txt
```
in README.md

**Comment by ONSKJ** [comment]
I thought I did but turns out I didn't :/

I got the script to run! However, I wasn't able to run it using the python interpreter directly.  Instead, I had to go to the exact location of the python file in my computer directory on the cmd and used `python tapas-dl.py [-h/--help] [-f/--force] [-v/--verbose] URL/name [URL/name ...] `

Thanks so much for the help!!

**Comment by ONSKJ** [comment]
I thought I did but turns out I didn't :/

I got the script to run! However, I wasn't able to run it using the python interpreter directly. Instead, I had to go to the exact (folder) location of the python file in my computer directory on the cmd and used `python tapas-dl.py [-h/--help] [-f/--force] [-v/--verbose] URL/name [URL/name ...]`

I did experience the same problem regarding unicode support when running the script for other comics but reading that issue I've realized there was an edited version of the code more suited towards windows ^^; so I'm going to try that one out

Thanks for the help!

**Comment by TilCreator** [comment]
I'm already working on a few fixes so that file names are accepted by Win (#6) and novel download support (#10), but it will be a few days due to hardware failure.

**Comment by TilCreator** [comment]
Also, it would be really nice if someone could help me to write a short section for the README.md about getting the script to run on Win. (I only have Linux machines)

**Comment by ONSKJ** [comment]
I'd be happy to help though I'm a bit new with coding and GitHub so my explanation might be confusing?

**Comment by TilCreator** [comment]
Just a list of things you had to do would be a huge help alone. ^^

**Comment by ONSKJ** [comment]
Basically this is what I did (have Windows 8)

- downloaded the zip file to my computer and extracted it

- downloaded python off the website (includes pip) 

- opened cmd prompt

- used `pip install requests` to download "requests" module

- changed directories in the cmd to the folder that held the python file and requirenments.txt file
example:
`cd Downloads\Tapas-Comics-Downloader-master`

- used `pip install -r requirenments.txt` while INSIDE the "Tapas-Comics-Downloader" folder to install the module 

- used `python tapas-dl.py [-h/--help] [-f/--force] [-v/--verbose] URL/name [URL/name ...]` to use script as needed

**Comment by TilCreator** [comment]
That was quick, thx very much, I will get back to it in a few days!

**Comment by TilCreator** [comment]
Added Windows install instruction, closing now
