### ISSUE TITLE
Cookies error

### ISSUE THREAD

**Issue by Pipixel** [TilCreator/Tapas-Comic-Downloader#33]
I don't understand why but when I want to put a cookie file it gives me an error that shows double backspaces

![cmd_COr2bb1l8F](https://user-images.githubusercontent.com/66361896/112754278-a4c64880-8fdb-11eb-8013-792b4aee6ba2.png)

**Comment by TilCreator** [comment]
The double `\` are normal, they are normally used to escape characters, not write file paths, so a `\` itself needs to be escaped with a `\`. It's been a few years since I used Python on Win, so I can only guess: Maybe try adding a `\` after the `C:` (`C:\User\...`) or just use `/` (`C:/User/...`). Or if all else fails just `cd` into the same directory as the cookie file and use relative paths.

**Comment by Pipixel** [comment]
Thank you. I also have another problem, once the series is finished downloading, the folder is deleted

**Comment by TilCreator** [comment]
Can you show me the whole log?

**Comment by Pipixel** [comment]
How can I do that?

**Comment by TilCreator** [comment]
Just send a screenshot of the command executing

**Comment by Pipixel** [comment]
![cmd_h814ry9no9](https://user-images.githubusercontent.com/66361896/112988212-e08c1a00-9163-11eb-8ec0-ea2d88edf51b.png)

**Comment by TilCreator** [comment]
I guess it's a comic?
It apparently detected the comic as a novel (that detection is sadly quite fragile).

**Comment by Pipixel** [comment]
this is exactly what I wanted to do, download the novel, I have the header downloader but once it's finish all has deleted

**Comment by TilCreator** [comment]
Oops, then I should revert that commit

**Comment by TilCreator** [comment]
Novels are not saved in a folder, but as epubs

**Comment by Pipixel** [comment]
I know but there is nothing, even the output file is deleted for some unknown reason

**Comment by TilCreator** [comment]
That is weird, I will try to replicate that

**Comment by TilCreator** [comment]
Try Writing the out path with `/` instead of `\` (`C:/Users/...`), if that works I know how to fix it.

**Comment by Pipixel** [comment]
I did it but it doesn't change anything

**Comment by TilCreator** [comment]
Weird, I will cleanup the saving code a bit more and maybe I will find something

**Comment by TilCreator** [comment]
Idk why that closed the issue, but that wasn't my intention

**Comment by Pipixel** [comment]
Thanks, now it works, but it is necessary to put the cookies file to access the other chapters?

**Comment by TilCreator** [comment]
Yes, sadly

**Comment by Pipixel** [comment]
Ok, thank you

**Comment by ONSKJ** [comment]
I've gotten a cookies errors as well, but a different one from the previous user. I am using a Netscape format cookie file, but it looks like it's missing the "update" attribute.

Particularly, I am not trying to get a mature comic, but rather use my login cookies to access comics that have been deleted from the site (licensing ran out or other reasons), but I can still access them on my account since I had bought them when they were available. Do you think this would be possible?

In any case being able to download my mature comics would be nice as well, so if someone can help me figure out the error it would be greatly appreciated ^^
